### ISSUE TITLE
hdf read error

### ISSUE THREAD

**Issue by rabernat** [blaze/dask#747]
I am trying to read an hdf5 file created with pytables into dask. I am calling

```python
f = dd.read_hdf(output_fname, '/floats/trajectories')
```

And getting the error
```
ValueError                                Traceback (most recent call last)
<ipython-input-6-d59a8b2bb0a1> in <module>()
----> 1 f = dd.read_hdf(output_fname, '/floats/trajectories')

/home/rpa/dask/dask/dataframe/io.py in read_hdf(pattern, key, start, stop, columns, chunksize)
    697     return concat([_read_single_hdf(path, key, start=start, stop=stop,
    698                                     columns=columns, chunksize=chunksize)
--> 699                    for path in paths])
    700 
    701 

/home/rpa/dask/dask/dataframe/io.py in _read_single_hdf(path, key, start, stop, columns, chunksize)
    651     from .multi import concat
    652     return concat([one_path_one_key(path, k, start, s, columns, chunksize)
--> 653                    for k, s in zip(keys, stops)])
    654 
    655 

/home/rpa/dask/dask/dataframe/io.py in one_path_one_key(path, key, start, stop, columns, chunksize)
    631         """
    632         if columns is None:
--> 633             columns = list(pd.read_hdf(path, key, stop=0).columns)
    634 
    635         token = tokenize((path, os.path.getmtime(path), key, start,

/usr/local/anaconda/lib/python2.7/site-packages/pandas/io/pytables.pyc in read_hdf(path_or_buf, key, **kwargs)
    330 
    331     try:
--> 332         return store.select(key, auto_close=auto_close, **kwargs)
    333     except:
    334         # if there is an error, close the store

/usr/local/anaconda/lib/python2.7/site-packages/pandas/io/pytables.pyc in select(self, key, where, start, stop, columns, iterator, chunksize, auto_close, **kwargs)
    672                            auto_close=auto_close)
    673 
--> 674         return it.get_result()
    675 
    676     def select_as_coordinates(

/usr/local/anaconda/lib/python2.7/site-packages/pandas/io/pytables.pyc in get_result(self, coordinates)
   1366 
   1367         # directly return the result
-> 1368         results = self.func(self.start, self.stop, where)
   1369         self.close()
   1370         return results

/usr/local/anaconda/lib/python2.7/site-packages/pandas/io/pytables.pyc in func(_start, _stop, _where)
    665             return s.read(start=_start, stop=_stop,
    666                           where=_where,
--> 667                           columns=columns, **kwargs)
    668 
    669         # create the iterator

/usr/local/anaconda/lib/python2.7/site-packages/pandas/io/pytables.pyc in read(self, where, columns, **kwargs)
   4039 
   4040             block = make_block(values, placement=np.arange(len(cols_)))
-> 4041             mgr = BlockManager([block], [cols_, index_])
   4042             frames.append(DataFrame(mgr))
   4043 

/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.pyc in __init__(self, blocks, axes, do_integrity_check, fastpath)
   2176 
   2177         if do_integrity_check:
-> 2178             self._verify_integrity()
   2179 
   2180         self._consolidate_check()

/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.pyc in _verify_integrity(self)
   2387         for block in self.blocks:
   2388             if not block.is_sparse and block.shape[1:] != mgr_shape[1:]:
-> 2389                 construction_error(tot_items, block.shape[1:], self.axes)
   2390         if len(self.items) != tot_items:
   2391             raise AssertionError('Number of manager items must equal union of '

/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.pyc in construction_error(tot_items, block_shape, axes, e)
   3525         raise e
   3526     raise ValueError("Shape of passed values is {0}, indices imply {1}".format(
-> 3527         passed,implied))
   3528 
   3529 

ValueError: Shape of passed values is (1, 0), indices imply (1, 753664023)
```

If helpful, I can post the h5dump of the file header. (It's really long.)

**Comment by rabernat** [comment]
I should also mention that I don't know whether pandas can read this or not--it is too big to fit into memory.

**Comment by mrocklin** [comment]
Try

pd.read_hdf(..., start=0, stop=10)

to get a few rows using pandas.

**Comment by shoyer** [comment]
In my experience, pandas struggles to read HDF5 files that were created with anything other than pandas. It uses pretty specific conventions for storing metadata.

**Comment by rabernat** [comment]
```python
pd.read_hdf(output_fname, '/floats/trajectories', start=0, stop=10)
````
gives
```
ValueError: Shape of passed values is (1, 10), indices imply (1, 753664023)
```

Frustrating. I guess this is a more general pandas issue.

I have hundreds of GB of data in this format. I was hoping to be able to use dask on it. Too bad...

**Comment by cowlicks** [comment]
You could try loading it into dask.array.

http://dask.pydata.org/en/latest/array-creation.html

**Comment by shoyer** [comment]
You might also be able to whip up a custom solution using `dd.from_array`.

Alternatively, I think there might be an easy way to construct a dask DataFrame out of dask arrays?

**Comment by rabernat** [comment]
Thanks a lot for the feedback.

I was able to load the data as a dask array, following the example from @cowlicks. This is useful progress. But none of the column names were imported.

I would like to be able to use the dataframe api, specifically groupby, on this dataset. So constructing a DataFrame out of the dask array would be ideal. Can't see exactly how to do that however.

**Comment by mrocklin** [comment]
You may find the dask.dataframe.from_dask_array function to be of use.

**Comment by cowlicks** [comment]
@rabernat did @mrocklin's suggestion work for you? If you have anymore questions we're happy to help.

**Comment by rabernat** [comment]
@cowlicks @mrocklin, really appreciate your help here.

dask.dataframe.from_dask_array did work in the sense that it did not raise any errors. However, the resulting dataframe is unusable. This is my complete workflow

```
import h5py
import dask
f = h5py.File(output_fname)
d = f['/floats/trajectories']
x = dask.array.from_array(d, chunks=(10000,))
ddf = dask.dataframe.from_dask_array(x)
```

But if I try to actually access the dataframe, e.g. ```ddf.head()```, I get the error

```

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-6-c69d295e43ff> in <module>()
----> 1 ddf.head()

/home/rpa/dask/dask/dataframe/core.pyc in head(self, n, compute)
    325 
    326         if compute:
--> 327             result = result.compute()
    328         return result
    329 

/home/rpa/dask/dask/base.pyc in compute(self, **kwargs)
     29 
     30     def compute(self, **kwargs):
---> 31         return compute(self, **kwargs)[0]
     32 
     33     @classmethod

/home/rpa/dask/dask/base.pyc in compute(*args, **kwargs)
     97                 for opt, val in groups.items()])
     98     keys = [arg._keys() for arg in args]
---> 99     results = get(dsk, keys, **kwargs)
    100     return tuple(a._finalize(a, r) for a, r in zip(args, results))
    101 

/home/rpa/dask/dask/threaded.pyc in get(dsk, result, cache, num_workers, **kwargs)
     55     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     56                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 57                         **kwargs)
     58 
     59     return results

/home/rpa/dask/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    489                 _execute_task(task, data)  # Re-execute locally
    490             else:
--> 491                 raise(remote_exception(res, tb))
    492         state['cache'][key] = res
    493         finish_task(dsk, key, state, results, keyorder.get)

NotImplementedError: compound dtypes are not implementedin the Series constructor

Traceback
---------
  File "/home/rpa/dask/dask/async.py", line 266, in execute_task
    result = _execute_task(task, data)
  File "/home/rpa/dask/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/series.py", line 141, in __init__
    dtype = self._validate_dtype(dtype)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 117, in _validate_dtype
    .format(self.__class__.__name__))
```

Since a compound dtype is the essence of tabular data, and the whole reason I wanted to use dataframe rather than array, this seems like a big limitation.

**Comment by rabernat** [comment]
> But none of the column names were imported.

Btw, in retrospect I was wrong about this. The column names were imported in the form of a numpy structured array.

I just want to be able to do groupby.

**Comment by mrocklin** [comment]
This may be resolved in https://github.com/blaze/dask/pull/759

**Comment by mrocklin** [comment]
@rabernat this should now work if you're on master branch.  Are you able to verify this?

**Comment by rabernat** [comment]
Yes, it works! :+1:

**Comment by mrocklin** [comment]
Great!   I'm going to close this for now.
