### ISSUE TITLE
Windows error in array/tests/test_random.py::test_concurrency

### ISSUE THREAD

**Issue by cowlicks** [blaze/dask#749]
Not sure about this one
```python
..\utils.py:65: WindowsError
______________________________ test_concurrency _______________________________

    def test_concurrency():
        state = da.random.RandomState(5)
        x = state.normal(10, 1, size=10, chunks=2)

        state = da.random.RandomState(5)
        y = state.normal(10, 1, size=10, chunks=2)
>       assert (x.compute(get=mpget) == y.compute(get=mpget)).all()

tests\test_random.py:29:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\base.py:31: in compute
    return compute(self, **kwargs)[0]
..\base.py:99: in compute
    results = get(dsk, keys, **kwargs)
..\multiprocessing.py:43: in get
    manager = multiprocessing.Manager()
..\..\..\..\..\anaconda\envs\dask\lib\multiprocessing\__init__.py:99: in Manager
    m.start()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <multiprocessing.managers.SyncManager object at 0x05031D70>
initializer = None, initargs = ()

    def start(self, initializer=None, initargs=()):
        '''
            Spawn a server process for this manager objectTraceback (most recent call last):

  File "<string>", line 1, in <module>
   File "c:\users\ieuser\anaconda\envs\dask\lib\multiprocessing\forking.py", line 380, in main
           '''    prepare(preparation_data)

  File "c:\users\ieuser\anaconda\envs\dask\lib\multiprocessing\forking.py", line 488, in prepare
            assert self._state.value == State.INITIALassert main_name not in sys.modules, main_name
AssertionError
:  _   _main__

        if initializer is not None and not hasattr(initializer, '__call__'):
            raise TypeError('initializer must be a callable')

        # pipe over which we will retrieve address of server
        reader, writer = connection.Pipe(duplex=False)

        # spawn process which runs a server
        self._process = Process(
            target=type(self)._run_server,
            args=(self._registry, self._address, self._authkey,
                  self._serializer, writer, initializer, initargs),
            )
        ident = ':'.join(str(i) for i in self._process._identity)
        self._process.name = type(self).__name__  + '-' + ident
        self._process.start()

        # get address of server
        writer.close()
>       self._address = reader.recv()
E       EOFError

..\..\..\..\..\anaconda\envs\dask\lib\multiprocessing\managers.py:528: EOFError

**Comment by cowlicks** [comment]
Not sure how to fix this. I tried made the relative imports in multiprocessing.py absolute. But now I get
```python 
distributed\tests\test_client.py::test_register_collections Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named forking
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named forking
FAILED
array\tests\test_random.py::test_concurrency Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named forking
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named forking
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named forking
FAILED
```

**Comment by jcrist** [comment]
This was discovered to be due to running tests in `dask/dask` directory. Closing.
