### ISSUE TITLE
Windows error in dask distributed 

### ISSUE THREAD

**Issue by cowlicks** [blaze/dask#752]
This looks similar to #749, the exception occurs at the same place in the multiprocessing scheduler.

```python
================================== FAILURES ===================================
__________________________ test_register_collections __________________________

    def test_register_collections():
        try:
            import dask.bag as db
        except ImportError:
            return
        with scheduler_and_workers() as (s, (a, b)):
            c = Client(s.address_to_clients)

            b = db.from_sequence(range(5), npartitions=2).map(inc)
            assert not s.collections
            c.set_collection('mybag', b)
            assert 'mybag' in s.collections

            d = Client(s.address_to_clients)
            b2 = d.get_collection('mybag')

            assert (type(b) == type(b2) and
                    b.npartitions == b2.npartitions)
>           assert list(b) == list(b2)

distributed\tests\test_client.py:113:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bag\core.py:711: in __iter__
    return iter(self.compute())
base.py:31: in compute
    return compute(self, **kwargs)[0]
base.py:99: in compute
    results = get(dsk, keys, **kwargs)
multiprocessing.py:43: in get
    manager = multiprocessing.Manager()
..\..\..\..\Anaconda\lib\multiprocessing\__init__.py:99: in Manager
    m.start()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <multiprocessing.managers.SyncManager object at 0x05094090>
initializer = None, initargs = ()

    def start(self, initializer=None, initargs=()):
        '''
            Spawn a server process for this manager object
            '''
        assert self._state.value == State.INITIAL

        if initializer is not None and not hasattr(initializer, '__call__'):
            raise TypeError('initializer must be a callable')

        # pipe over which we will retrieve address of server
        reader, writer = connection.Pipe(duplex=False)

        # spawn process which runs a server
        self._process = Process(
            target=type(self)._run_server,
            args=(self._registry, self._address, self._authkey,
                  self._serializer, writer, initializer, initargs),
            )
        ident = ':'.join(str(i) for i in self._process._identity)
        self._process.name = type(self).__name__  + '-' + ident
        self._process.start()

        # get address of server
        writer.close()
>       self._address = reader.recv()
E       EOFError

..\..\..\..\Anaconda\lib\multiprocessing\managers.py:528: EOFError
========================== 1 failed in 5.10 seconds ===========================

**Comment by cowlicks** [comment]
I missed part of the traceback, an important part:
```python
PS C:\Users\IEUser\Documents\GitHub\dask\dask> py.test -s -vv .\distributed\tests\test_client.py::test_register_collecti
ons
============================= test session starts =============================
platform win32 -- Python 2.7.10 -- py-1.4.27 -- pytest-2.7.1 -- C:\Users\IEUser\Anaconda\python.exe
rootdir: C:\Users\IEUser\Documents\GitHub\dask, inifile:
collected 10 items

distributed\tests\test_client.py::test_register_collections Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing.py", line 4, in <module>
    from .optimize import fuse, cull
ValueError: Attempted relative import in non-package
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing.py", line 4, in <module>
    from .optimize import fuse, cull
ValueError: Attempted relative import in non-package
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing.py", line 4, in <module>
    from .optimize import fuse, cull
ValueError: Attempted relative import in non-package
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing.py", line 4, in <module>
    from .optimize import fuse, cull
ValueError: Attempted relative import in non-package
FAILED

================================== FAILURES ===================================
__________________________ test_register_collections __________________________

    def test_register_collections():
```

I think this is a bug in python's pickling or multiprocessing. Same as this SO question https://stackoverflow.com/questions/26041404/python-windows-and-multiprocessing

**Comment by mrocklin** [comment]
I suggest that we skip dealing with distributed issues.

**Comment by cowlicks** [comment]
@mrocklin I agree. But I think this is a windows multiprocessing issue. It is probably caused by the same thing as #749. So fixing #749 would fix this.

**Comment by mrocklin** [comment]
OK

**Comment by jcrist** [comment]
This was discovered to be due to running tests in `dask/dask` directory. Closing.
