### ISSUE TITLE
Error when slicing dask dataframes 

### ISSUE THREAD

**Issue by fjanoos** [blaze/dask#862]
Hello,

This is an error regarding the output of _loc_slice when slicing a dataframe that was read from a csv. 

The problem seems to arise that with a csv, partition boundaries are not known before hand and I have to manually fix them as follows

``` python
import dask.dataframe as ddf
my_ddf = ddf.read_csv('myfile.csv', chunkbytes=1000 ) # force multiple partitions
partition_lens = my_ddf.map_partitions(len).compute() # get partition boundaries
unk_divisions = [0]
unk_divisions.extend(cumsum( partition_lens ))
my_ddf.divisions = tuple(unk_divisions)

print( my_ddf.divisions )
```
![image](https://cloud.githubusercontent.com/assets/923438/11593593/1b02109c-9a73-11e5-9121-d59a18d2fe6d.png)

Issue 1: Slicing *within* a division breaks  the [inclusive, exclusive) semantics of python / pandas.

```
my_ddf.loc[3:6].compute()
```
![image](https://cloud.githubusercontent.com/assets/923438/11593626/40cae092-9a73-11e5-96a0-2702e659bf18.png)

Issue 2: Slicing *across* divisions (for a csv file read and fixed in this fashion) dumps the whole table and doesn't return the correct indices

```
my_ddf.loc[8:11].compute()
```
![image](https://cloud.githubusercontent.com/assets/923438/11593648/5f6511e4-9a73-11e5-9b02-e223b75dd688.png)

**Comment by mrocklin** [comment]
Hi @fjanoos,

Cool trick adding the proper index to a CSV-read dataframe.  This might actually make a nice option to add into `dask.dataframe.read_csv` if you're interested in making a contribution

### [inclusive, inclusive]

Oddly, `pandas.DataFrame.loc` is inclusive on both ends, defying Python conventions.

```python
In [1]: import pandas as pd

In [2]: pd.DataFrame({'x': range(10)}).loc[3:6]
Out[2]: 
   x
3  3
4  4
5  5
6  6
```

My guess is that this made more sense for time series applications.  In either event, `dask.dataframe` follows `pandas`' lead on API decisions.

### Slicing across divisions

The internal dataframes still have an improper index, going from 0 to n rather than from `unk_divisions[i] to unk_divisions[i + 1]`.  You would need to change those in the same way you change the divisions.  I might do something explicit with the internal API as follows:

```python
def bump_index(df, i):
    df = df.copy()
    df.index = df.index + i
    return df

name = 're-index-' + tokenize(df, unk_divisions)
dsk = {(name, i): (bump_index, (my_ddf._name, i), div) 
           for i, div in enumerate(unk_divisions)}
return dd.DataFrame(dsk, name, my_ddf.columns, unk_divisions)
```

**Comment by fjanoos** [comment]
@mrocklin 

The pandas  (version 0.17.0') I'm using has [, ) indexing:
```
my_df = DataFrame( randn(1000,10))
my_df[3:5]
```
![image](https://cloud.githubusercontent.com/assets/923438/11594244/ee63d666-9a76-11e5-9b77-ffd5f32f18de.png)

Ah - I get your point about the internal index. I'll fix it up and send you a snippet for review ?

Thanks.

**Comment by fjanoos** [comment]
You're right - df.loc has [incl, incl] indexing. Bizarre semantics, that.

**Comment by martindurant** [comment]
`df.loc` is label-based indexing, which is inclusive (e.g., consider selecting a set of columns) - it just so happens that in your example, the label and positional indexes share the same values. 
`df[start:end]` is actually positional indexing like `.iloc` . For pandas, the style of object in the square brackets affects the type of indexing, and loc/iloc are recommended to be explicit.

**Comment by fjanoos** [comment]
I'm having some trouble fixing the indices. This is how I attempted to solve the indexing problem, so that  we don't have to copy over the df. 

``` python
# this function takes the dask tuple that created the original dataframe and fixes it indices
def fix_indices( dv , seix):
    '''
    :param dv Take as input a dask action tuple that encapsulates a dataframe.
    :param seix: Tuple of start and end indices
    Use dask imperative to execute that tuple.
    Thunk it's indices based on start and end indices
    '''    
    print(dv)
    df = imperative.do(dv[0])(*dv[1:]).compute();
    df.index = range( seix[0], seix[1] )
    return df;

dsk = raw_ddf.dask  # get the original dask graph
ddf_divisions = [0]+[None]*len(date_ranges)
partition_lens = raw_ddf.map_partitions(len).compute() # has to scan through the data once...
ddf_divisions[1:] = cumsum( partition_lens )
raw_ddf.divisions = tuple(ddf_divisions) # fix the divisions of the original ddf

# construct a dictionary of division number and its start and end indices
seix_map = dict( zip(range(len(ddf_divisions)-1) , zip(ddf_divisions[0:-1], ddf_divisions[1:]) ) )
# fix the indices for each df
dskfix = dict()
# iterate over each division in the original dask dataframe
for dk in dsk.keys():
    cdiv = dk[1]; # current division
    dskfix[dk] = (fix_indices, dsk[dk], seix_map[cdiv] )

fix_ddf = ddf.DataFrame(dskfix, 'ddf', cols, ddf_divisions)
```

This approach fixes the indexes, but destroys the dataframe property. By that I mean, now fix_ddf has become a series.  For example, when I type
```
fix_ddf.head()
```
It prints out the whole table.

Same problem when I type
```
len(fix_ddf
```
![image](https://cloud.githubusercontent.com/assets/923438/11603408/90e1570a-9aaf-11e5-80f8-14e8162bf4ab.png)

**Comment by fjanoos** [comment]
The reason I'm doing it this way is that, rather than read from a csv, I wanted to use pandas read_csv to stream in data from a pipe. So, my full code is somethign like this:

``` python
uri = 'smooth:/research/user/firdaus/test_fjpy/v1/US/factorTable' # the url of my data
date_ranges = [(20140601, 20140602), (20140602, 20140603), (20140603, 20140604)]

from tempfile import mkdtemp
from joblib import Memory
from toolz import first
import dask.imperative as imperative
import dask.dataframe as ddf
from fjpy.utils import dcat_reader as fjdcr  

cachedir = mkdtemp()
memory = Memory(cachedir=cachedir, verbose=0)
dcr = fjdcr.dcatReader(uri); # this returns a subprocess pipe object

@memory.cache
def cached_read_csv(start, end, div):
    df = pd.read_csv(dcr.get_pipe(start, end))
    return df;

def fix_indices( dv , seix):
    '''
    :param dv Take as input a dask action tuple that encapsulates a dataframe.
    :param seix: Tuple of start and end indices
    Use dask imperative to execute that tuple.
    Thunk it's indices based on start and end indices
    '''    
    print(dv)
    df = imperative.do(dv[0])(*dv[1:]).compute();
    df.index = range( seix[0], seix[1] )
    return df;

dsk = {  ('ddf', i): (cached_read_csv, start, end, i) for i, (start, end) in enumerate(date_ranges)   }
ddf_divisions = [0]+[None]*len(date_ranges)
cols = cached_read_csv(date_ranges[0][0],date_ranges[0][1], 0).columns
raw_ddf = ddf.DataFrame(dsk, 'ddf', cols, ddf_divisions)
partition_lens = raw_ddf.map_partitions(len).compute() # has to scan through the data once...
ddf_divisions[1:] = cumsum( partition_lens )
raw_ddf.divisions = tuple(ddf_divisions)

# construct a dictrionary of division number and start and end indices
seix_map = dict( zip(range(len(ddf_divisions)-1) , zip(ddf_divisions[0:-1], ddf_divisions[1:]) ) )
# fix the indices for each df
dskfix = dict()
for dk in dsk.keys():
    cdiv = dk[1]; # current division
    dskfix[dk] = (fix_indices, dsk[dk], seix_map[cdiv] )

fix_ddf = ddf.DataFrame(dskfix, 'ddf', cols, ddf_divisions)

```

**Comment by mrocklin** [comment]
This

    df = imperative.do(dv[0])(*dv[1:]).compute();

Is the same as this

    df = dv[0](dv[1:])

Recall that the contents of the tuples are just Python functions, you can run them as you like.

However, functions with a dask graph will never receive a tuple, they'll receive the value computed by that tuple, so `fix_indices` should expect to get a full `pandas.DataFrame` back, not a tuple.

```python
dsk = {'x': 1, 'y': (func, 'x')}

def func(x):
    return type(x)

>>> get(dsk, 'y')
int
```

I wouldn't worry too much about copying over the dataframe.  I'm not confident about this, but it's probably not doing a deepcopy.

However, if you want to keep with your current strategy you could use a function like the following:

```python
def fix_indices( df, seix):
    df.index = range(seix[0], seix[1])  # warning mutation
    return df

dsk = {(new_name, i): (fix_indices, (name, i), seix) for i, seix in enumerate(...)}
```

Just now seeing your update, will post this and then read.

**Comment by mrocklin** [comment]
Does your data fit in memory?  If so why are you using `read_csv` rather than a function like `from_pandas`?

**Comment by fjanoos** [comment]
My dataset is 100GB so it doesn't fit in memory. Also, it is hosted remotely - and making a local CSV copy seems kinda circuitous. I am looking for a solution where I can pipe/stream my data into the dask divisions. I currently stream in chunks of it into pandas dataframes using subprocess.pipe, but that limits me to operating on ~20GB chunks.

Also, this does *not* work for me:

``` python
uri = 'smooth:/research/user/firdaus/test_fjpy/v1/US/factorTable' # the url of my data
date_ranges = [(20140601, 20140602), (20140602, 20140603), (20140603, 20140604)]

from tempfile import mkdtemp
from joblib import Memory
from toolz import first
import dask.imperative as imperative
import dask.dataframe as ddf
from fjpy.utils import dcat_reader as fjdcr  

cachedir = mkdtemp()
memory = Memory(cachedir=cachedir, verbose=0)
dcr = fjdcr.dcatReader(uri); # this returns a subprocess pipe object

@memory.cache
def cached_read_csv(start, end, div):
    df = pd.read_csv(dcr.get_pipe(start, end))
    return df;

def bump_index(df, i):
    print(df)
    df = df.copy()
    df.index = df.index + i
    return df

dsk = {  ('ddf', i): (cached_read_csv, start, end, i) for i, (start, end) in enumerate(date_ranges)   }
ddf_divisions = [0]+[None]*len(date_ranges)
cols = cached_read_csv(date_ranges[0][0],date_ranges[0][1], 0).columns
raw_ddf = ddf.DataFrame(dsk, 'ddf', cols, ddf_divisions)
partition_lens = raw_ddf.map_partitions(len).compute() # has to scan through the data once...
ddf_divisions[1:] = cumsum( partition_lens )
raw_ddf.divisions = tuple(ddf_divisions)

name = 're-index' 
dsk = { (name, i): (bump_index, (raw_ddf._name, i), div)  for i, div in enumerate(ddf_divisions) }
fix_ddf = ddf.DataFrame(dsk, name, raw_ddf.columns, ddf_divisions)
```

```
fix_ddf.head()
```

```
('ddf', 0)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-9203b1713db8> in <module>()
----> 1 fix_ddf.head()

/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/dask/dataframe/core.py in head(self, n, compute)
    338 
    339         if compute:
--> 340             result = result.compute()
    341         return result
    342 

/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/dask/base.py in compute(self, **kwargs)
     35 
     36     def compute(self, **kwargs):
---> 37         return compute(self, **kwargs)[0]
     38 
     39     @classmethod

/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/dask/base.py in compute(*args, **kwargs)
    108                 for opt, val in groups.items()])
    109     keys = [var._keys() for var in variables]
--> 110     results = get(dsk, keys, **kwargs)
    111 
    112     results_iter = iter(results)

/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     55     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     56                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 57                         **kwargs)
     58 
     59     return results

/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    479                 _execute_task(task, data)  # Re-execute locally
    480             else:
--> 481                 raise(remote_exception(res, tb))
    482         state['cache'][key] = res
    483         finish_task(dsk, key, state, results, keyorder.get)

AttributeError: 'tuple' object has no attribute 'copy'

Traceback
---------
  File "/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/dask/async.py", line 264, in execute_task
    result = _execute_task(task, data)
  File "/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/dask/async.py", line 246, in _execute_task
    return func(*args2)
  File "<ipython-input-14-2d0fc8baa645>", line 25, in bump_index
    df = df.copy()

```

**Comment by mrocklin** [comment]
Oh dear, I see that the example I gave you a while ago was broken.  We need to include all of the key-value pairs of the old dask graph (the one from `dd.read_csv`) in the new DataFrame.  I've made the edit in the original comment.  I'm also including it here below.

```python
dsk = {(name, i): (bump_index, (my_ddf._name, i), div) 
           for i, div in enumerate(unk_divisions)}

dsk.update(my_ddf.dask)  # add in old key/value pairs

return dd.DataFrame(dsk, name, my_ddf.columns, unk_divisions)
```

**Comment by fjanoos** [comment]
Also, my original solution works -- in that the data is available. Only problem is that it doesn't seem to be a dataframe.  For my first approach, this is what the dask graph looks like:

The raw ddf graph (ie without fixing indices):
```
raw_ddf.dask
```

```
{('ddf',
  0): (MemorizedFunc(func=<function cached_read_csv at 0x7fcd9dc04f28>, cachedir='/tmp/tmpmz9w4ds3/joblib'), 20140601, 20140602, 0),
 ('ddf',
  1): (MemorizedFunc(func=<function cached_read_csv at 0x7fcd9dc04f28>, cachedir='/tmp/tmpmz9w4ds3/joblib'), 20140602, 20140603, 1),
 ('ddf',
  2): (MemorizedFunc(func=<function cached_read_csv at 0x7fcd9dc04f28>, cachedir='/tmp/tmpmz9w4ds3/joblib'), 20140603, 20140604, 2)}
```

After fixing the indices:
```
fix_ddf.dask
```

```
{('ddf', 0): (<function __main__.fix_indices>,
  (MemorizedFunc(func=<function cached_read_csv at 0x7fcd9dc04f28>, cachedir='/tmp/tmpmz9w4ds3/joblib'),
   20140601,
   20140602,
   0),
  (0, 3929)),
 ('ddf', 1): (<function __main__.fix_indices>,
  (MemorizedFunc(func=<function cached_read_csv at 0x7fcd9dc04f28>, cachedir='/tmp/tmpmz9w4ds3/joblib'),
   20140602,
   20140603,
   1),
  (3929, 11792)),
 ('ddf', 2): (<function __main__.fix_indices>,
  (MemorizedFunc(func=<function cached_read_csv at 0x7fcd9dc04f28>, cachedir='/tmp/tmpmz9w4ds3/joblib'),
   20140603,
   20140604,
   2),
  (11792, 19654))}
```


This is the code that generated it:
``` python
uri = 'smooth:/research/user/firdaus/test_fjpy/v1/US/factorTable'
date_ranges = [(20140601, 20140602), (20140602, 20140603), (20140603, 20140604)]

from tempfile import mkdtemp
from joblib import Memory
from toolz import first
import dask.imperative as imperative
import dask.dataframe as ddf
from fjpy.utils import dcat_reader as fjdcr
reload(fjdcr)

cachedir = mkdtemp()
memory = Memory(cachedir=cachedir, verbose=0)
dcr = fjdcr.dcatReader(uri);

@memory.cache
def cached_read_csv(start, end, div):
    df = pd.read_csv(dcr.get_pipe(start, end))
    return df;

def fix_indices( dv , seix):
    '''
    :param dv Take as input a dask action tuple that encapsulates a dataframe.
    :param seix: Tuple of start and end indices
    Use dask imperative to execute that tuple.
    Thunk it's indices based on start and end indices
    '''    
    print(dv)
    df = imperative.do(dv[0])(*dv[1:]).compute();
    df.index = range( seix[0], seix[1] )
    return df;

dsk = {  ('ddf', i): (cached_read_csv, start, end, i) for i, (start, end) in enumerate(date_ranges)   }
ddf_divisions = [0]+[None]*len(date_ranges)
cols = cached_read_csv(date_ranges[0][0],date_ranges[0][1], 0).columns
raw_ddf = ddf.DataFrame(dsk, 'ddf', cols, ddf_divisions)
partition_lens = raw_ddf.map_partitions(len).compute() # has to scan through the data once...
ddf_divisions[1:] = cumsum( partition_lens )
raw_ddf.divisions = tuple(ddf_divisions)

# construct a dictrionary of division number and start and end indices
seix_map = dict( zip(range(len(ddf_divisions)-1) , zip(ddf_divisions[0:-1], ddf_divisions[1:]) ) )
# fix the indices for each df
dskfix = dict()
for dk in dsk.keys():
    cdiv = dk[1]; # current division
    dskfix[dk] = (fix_indices, dsk[dk], seix_map[cdiv] )

fix_ddf = ddf.DataFrame(dskfix, 'ddf', cols, ddf_divisions)
```

**Comment by mrocklin** [comment]
Alrighty, if a solution works it works!

**Comment by fjanoos** [comment]
Except when it doesn't :) 
As I mentioned earlier, when I do it this way, even something like
```
len(fix_ddf)
```
prints out the *whole* table. So somehow dask is confused about the type of fix_ddf.

At this point *any* solution would be appreciated !

**Comment by mrocklin** [comment]
I still think that the solution I gave above (with the edits) is the right way forward here.

In terms of length computing the whole table this is probably unavoidable.  There's no way to determine the length of a `dask.dataframe` strictly from metadata.  In this particular case we could looking `df.divisions[-1]` would be correct, but there is no way to guarantee that.  The pandas index holds values, not numerical index locations.  The only way to determine the length of a dask.dataframe is to compute the length of all of the partitions and then add them up.

**Comment by mrocklin** [comment]
I may not fully understand what you're trying to do here though.  My apologies if this is a frustrating experience.

**Comment by fjanoos** [comment]
Ah. Figured it out. There was a print(dv) in the fix_indices that was dumping the whole table. False herrring. It all works !

**Comment by fjanoos** [comment]
Thanks !

**Comment by mrocklin** [comment]
Is this issue resolved?  Can it be closed?

**Comment by fjanoos** [comment]
yes. Thanks.
